
import java.awt.Frame;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Laura
 */
public class Principal extends javax.swing.JFrame {
    
    Hilo hilo1 = new Hilo();
    Hilo hilo2 = new Hilo();
    Hilo hilo3 = new Hilo();
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        hilo1.window = 1;
        hilo1.start();
        hilo2.window = 2;
        hilo2.start();
        hilo3.window = 3;
        hilo3.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(590, 370));
        setMinimumSize(new java.awt.Dimension(590, 370));
        setUndecorated(true);

        jPanel1.setMaximumSize(new java.awt.Dimension(590, 370));
        jPanel1.setMinimumSize(new java.awt.Dimension(590, 370));
        jPanel1.setPreferredSize(new java.awt.Dimension(590, 370));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Detener.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setMaximumSize(new java.awt.Dimension(70, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(70, 25));
        jButton3.setPreferredSize(new java.awt.Dimension(70, 25));
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Detener_P.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 235, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cereza.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setMaximumSize(new java.awt.Dimension(170, 170));
        jLabel3.setMinimumSize(new java.awt.Dimension(170, 170));
        jLabel3.setPreferredSize(new java.awt.Dimension(170, 170));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 45, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cereza.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(170, 170));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 45, -1, -1));

        jButton2.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Detener.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMaximumSize(new java.awt.Dimension(70, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(70, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(70, 25));
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Detener_P.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 235, -1, -1));

        jButton4.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Detener_Todos.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setMaximumSize(new java.awt.Dimension(102, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(102, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(128, 25));
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Detener_Todos_P.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 280, -1, -1));

        jButton5.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Iniciar.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setMaximumSize(new java.awt.Dimension(60, 25));
        jButton5.setMinimumSize(new java.awt.Dimension(60, 25));
        jButton5.setPreferredSize(new java.awt.Dimension(64, 25));
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Iniciar_P.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 325, -1, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cereza.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(170, 170));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, -1, -1));

        jButton1.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Detener.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(70, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(70, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(70, 25));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Detener_P.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 235, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Salir.png"))); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setMaximumSize(new java.awt.Dimension(23, 23));
        jButton6.setMinimumSize(new java.awt.Dimension(23, 23));
        jButton6.setPreferredSize(new java.awt.Dimension(30, 23));
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Salir_P.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Minimizar.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setMaximumSize(new java.awt.Dimension(23, 23));
        jButton7.setMinimumSize(new java.awt.Dimension(23, 23));
        jButton7.setPreferredSize(new java.awt.Dimension(30, 23));
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Minimizar_P.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Victoria(){
        if ((hilo1.resultado == hilo2.resultado)&&(hilo2.resultado == hilo3.resultado)&&(hilo1.resultado!=0)){
            Mensaje gana = new Mensaje();
            gana.setVisible(true);
        }
    }
    
    public class Hilo extends Thread{
        public int window = 0;  
        public int resultado = 0;
        private boolean run = false;
        
        public void startRunning(){
            run = true;
        }
        public void stopRunning(){
            run = false;
        }
        public boolean isRunning(){
            return run;
        }
        public int getRandom(){
            int random = (int) (Math.random() * 4 + 1);
            return random;
        }
        
        @Override
        public void run(){
            int tiempo = 100;
            Image img;
            while (window == 1){
                jLabel1.setText(jLabel1.getText());
                while (run){    
                    if (this.getRandom()==1){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/Cereza.png")).getImage();
                        resultado = 1;
                    }
                    else if (this.getRandom()==2){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/Naranja.png")).getImage();
                        resultado = 2;
                    }
                    else if (this.getRandom()==3){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/Pera.png")).getImage();
                        resultado = 3;
                    }
                    else{
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/Pina.png")).getImage();
                        resultado = 4;
                    }
                    jLabel1.setIcon(new ImageIcon(img));
                    try{
                        Thread.sleep(tiempo);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            while (window == 2){
                jLabel2.setText(jLabel2.getText());
                while (run){    
                    if (this.getRandom()==1){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/Cereza.png")).getImage();
                        resultado = 1;
                    }
                    else if (this.getRandom()==2){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/Naranja.png")).getImage();
                        resultado = 2;
                    }
                    else if (this.getRandom()==3){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/Pera.png")).getImage();
                        resultado = 3;
                    }
                    else{
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/Pina.png")).getImage();
                        resultado = 4;
                    }
                    jLabel2.setIcon(new ImageIcon(img));
                    try{
                        Thread.sleep(tiempo);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            while (window == 3){
                jLabel3.setText(jLabel3.getText());
                while (run){    
                    if (this.getRandom()==1){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/Cereza.png")).getImage();
                        resultado = 1;
                    }
                    else if (this.getRandom()==2){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/Naranja.png")).getImage();
                        resultado = 2;
                    }
                    else if (this.getRandom()==3){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/Pera.png")).getImage();
                        resultado = 3;
                    }
                    else{
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/Pina.png")).getImage();
                        resultado = 4;
                    }
                    jLabel3.setIcon(new ImageIcon(img));
                    try{
                        Thread.sleep(tiempo);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Detiene Ventana 1
        hilo1.stopRunning();
        if((!hilo2.isRunning())&&(!hilo3.isRunning())){
            Victoria();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Cierra el programa
        hilo1.stop();
        hilo2.stop();
        hilo3.stop();
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Minimiza el programa
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Empieza el programa
        hilo1.startRunning();
        hilo2.startRunning();
        hilo3.startRunning();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Detiene todas las ventanas
        hilo1.stopRunning();
        hilo2.stopRunning();
        hilo3.stopRunning();
        Victoria();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Detiene Ventana 2
        hilo2.stopRunning();
        if((!hilo1.isRunning())&&(!hilo3.isRunning())){
            Victoria();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Detiene Ventana 3
        hilo3.stopRunning();
        if((!hilo2.isRunning())&&(!hilo1.isRunning())){
            Victoria();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
